// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBFjMUKwgZpt10ju3QIf2aYaFkSebRbK4',
    appId: '1:569521470942:web:57dacdda7055757766f14f',
    messagingSenderId: '569521470942',
    projectId: 'sportilife',
    authDomain: 'sportilife.firebaseapp.com',
    storageBucket: 'sportilife.firebasestorage.app',
    measurementId: 'G-68MPT6H92N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3YvK4z3TCuOjh-EsGO5hB67XvY-BVoNA',
    appId: '1:569521470942:android:c8a9dbfb79ede09466f14f',
    messagingSenderId: '569521470942',
    projectId: 'sportilife',
    storageBucket: 'sportilife.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXAcgL-Wtyvt2J9i7ckgTPxFElNlwm7RQ',
    appId: '1:569521470942:ios:274194ba9af6930866f14f',
    messagingSenderId: '569521470942',
    projectId: 'sportilife',
    storageBucket: 'sportilife.firebasestorage.app',
    iosBundleId: 'com.example.sportApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXAcgL-Wtyvt2J9i7ckgTPxFElNlwm7RQ',
    appId: '1:569521470942:ios:274194ba9af6930866f14f',
    messagingSenderId: '569521470942',
    projectId: 'sportilife',
    storageBucket: 'sportilife.firebasestorage.app',
    iosBundleId: 'com.example.sportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBFjMUKwgZpt10ju3QIf2aYaFkSebRbK4',
    appId: '1:569521470942:web:983b1e5b24c8f37a66f14f',
    messagingSenderId: '569521470942',
    projectId: 'sportilife',
    authDomain: 'sportilife.firebaseapp.com',
    storageBucket: 'sportilife.firebasestorage.app',
    measurementId: 'G-B6MMNFTZHP',
  );
}
